#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Math-Fibonacci-Phi
version:      0.01
version_from: Phi.pm
installdirs:  site
requires:
    Math::Fibonacci:               0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
